### ISSUE TITLE
Flux implementation

### ISSUE THREAD

**Issue by goatslacker** [wbkd/react-isomorphic-example#1]
I wanted to point out [alt](https://github.com/goatslacker/alt) which is a pure flux implementation written in ES6, and isomorphic ready out of the box. I thought you'd be interested because the starter kits seem to be ES6 focused.

You can check out an example app (the flux chat app) [here](https://github.com/goatslacker/alt/tree/master/examples/chat).

**Comment by moklick** [comment]
Thanks :+1:  we will check that

**Comment by goatslacker** [comment]
Closing this in lieu of https://github.com/wbkd/react-starterkit/pull/1
